language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: AKIAITP7YTN5FG46FS4Q
  bucket: andyc.hacku.pfp-cicd
  region: us-west-2
  secret_access_key:
    secure: RKYqcFXDgqnSGzYIVBmotNv74Vh5nzfOZl5OnnLouTwn5m19jNtvNP/dp1/GpsqSUYna9V6qnT25+06+xIdEfLkLQY7wWaXEVY2txrPQwwQ/lHL7adX6QBhfw1gFtN3HbcLN0NzKRbWOAD0ZD9T5iFpcbb7YDphwBe4uZGNLvPa19y5+bnZEAJs8sSEYolmY8v4vShO5+26w22m30P7/eDwgnuPTYr2y5+D57zZ/CXv/iIpcRvVVHq43+DmtlXbKtUdVi8HDAqvIUfogoNkAS6NEd8agzgX2ZKbN7w3WHkhBt7j1A/9don67jG84klDT8BwMKqi0VKOQyKY6eFsVTiy/NhZpEEt/+zIq5Cv5JgEeZurpVgP6jysyIb1+HOGwUSoXY0Yqg1Iavfi8g+a6QOnIL8mbhEnCVaN7a23Vue6ru7AHaN3AK/bQn5oEpwcVx2O3krwbyCeU/WmClJxkfH1d3jrytXebyknbOjfwILTMysjUE79Pgd6dOnWXar4JR2Lyd7R+ay80GPSi7mxDdOx9iGJ6+nlpamFme2Xoa1XBKqFxuwlsQ+Zk+C2g+t4/yUSs5ONhanm1YbM5oW9P9WBApLbm1vyAueFmLpzYEONe8aYnLTwFb1+QjwWIm4ReE7SEIx0vLEJvYSAbeqMqq4eP1C9RjsLOEGUC2ncUIWk=
