language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: AKIAJ72FSS4SHIPEWOBQ
  bucket: andyc.hacku.pfp-cicd
  region: us-west-2
  secret_access_key:
    secure: pUWKmeIQM39OIn1lEKFQNDo4Rddfo7X9ajRtsfUulxKCWVWg/MvhdlaefhL1uPQ9042eV8+MCutOTjHev0tE+GzEPC5VjQiudJochPcvo35FZ9us4XP3TCjjgSUsgLP5H+DAG4we5Z393652uBDtlCsXbK8k8DdEtXSGa95DvxqC2npXw8/GXV+v+kQIdvTzYLmEM/Ugcj2XkkSJtYDrpSXGXZZRQiuLo6sHXvLdUwEQcEHlHwIWsxoPUufVuMJQkcQY/Z3Yg0sPoa+zEdGOH3JiSp/Ub3NeGp4drDlKYLl+QuqFA7gmUnO6MJJ68pM3BMcRAvhSyapztkMReiI8u/8IKRxdgCIr4cP5UwdEVjbO14eCSVS4zB079Quu3i8Fg1t0JAsq8VnesvUpRr+dhBl7Bmz81Iend4E82EbsJ+K/mSng6rEdVz10M/LGXg37JHWVURWtXDNfgnHexqnz7/9AQwnUmPb8S+YBr9i88Dx8uDsbtlEj88gq2YhCO2vP5KEPbr1Cj/5RYoAodCJEzSXADd8e6Gb619T+w2f1fiPBUCjDbwhkPtCIM0Lc29psCnveiy6pS7HWhIjOra0qvk64t1bWzJbrJlKoE1Yfph9e+iuR9i3ViMnEIyC9dFnG+4hDoIpX9Yktf2tSZ9NtTxcm6l4TBLCQvZIut6Pjx/w=
