before_install: npm install mocha 
language: node_js
node_js:
- '6.0'
install: npm install
deploy:
  provider: s3
  access_key_id: AKIAJ72FSS4SHIPEWOBQ
  bucket: andyc.hacku.php-cicd
  region: us-west-2
  secret_access_key:
    secure: rDjRUqGbS9waIYBsDNRe4rT4Yf72r2y9D4y5Khb2Iq7sUtqOl0k96BVgh5FRTFZdCoOzsI+dxAyd2sBkexWaulSY3pRkRrHdBoCqNrNJp39hCI65YElzJK5O1pTSbCeJ9xCovQh5qH0ek+6UfU/YpC+UiiYqKaMGV4aXIhGtSw4HeNM8jjHrFfPRwRiupTwgQCVHkdVQJFjQwco0aEoD82g2HKYMtFVXQ2ccHz4Znu3rUoFiIUbwe00lTq7OzHbGcsrj8g7kHoaSPIpQciQ+U7A+ztmMHgZAT0OdzGfSH3VhoUW/octnC+vUHjnQQ+f/nyALvEcPajW7Y3AvyezecvitqMiYvyjRLcqBHQxn90I55VO2oF3ETw9s/sYL9byEuitcnYQK8WcgFg4fCGLLaic0l+KleLIAxMmgrvlKaGYg3q+LFXzcObLqAWy5jBVf34xz06g+vQh9km8wrUYPrteC9gZ+PEJ3/hqJepKcvGIDSgHDezzMsDL4UvY+aWOQr+sBjxqRfSOZLsrxFtOEo/BWAWz2T4vDH+d2XZjakdTsDA5LC6JysIDazx+6S9Tjbl41atrKeFwdCU/6vw3oSBM5omwXTjC8DbAwbEZ0Zei38LcAkZ+7/RU5ZS7sJXftib5QhYceqxypjCeXzS/oOVv6SMR7vH2yd6FC1DulZfg=
